/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as todoRouteRouteImport } from './routes/(todo)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as todoTodoRouteImport } from './routes/(todo)/todo'

const todoRouteRoute = todoRouteRouteImport.update({
  id: '/(todo)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const todoTodoRoute = todoTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => todoRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todo': typeof todoTodoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todo': typeof todoTodoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(todo)': typeof todoRouteRouteWithChildren
  '/(todo)/todo': typeof todoTodoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todo'
  id: '__root__' | '/' | '/(todo)' | '/(todo)/todo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  todoRouteRoute: typeof todoRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(todo)': {
      id: '/(todo)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof todoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(todo)/todo': {
      id: '/(todo)/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof todoTodoRouteImport
      parentRoute: typeof todoRouteRoute
    }
  }
}

interface todoRouteRouteChildren {
  todoTodoRoute: typeof todoTodoRoute
}

const todoRouteRouteChildren: todoRouteRouteChildren = {
  todoTodoRoute: todoTodoRoute,
}

const todoRouteRouteWithChildren = todoRouteRoute._addFileChildren(
  todoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  todoRouteRoute: todoRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
